import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <h2>This is navbar</h2>
          <Link href="/">Dashboard</Link>
          <br />
          <Link href="/tickets">Tickets</Link>
        </nav>
        {children}
      </body>
    </html>
  )
}
